/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerListReplyData = zod.object({
  boxers: zod
    .array(
      zod.object({
        boxerId: zod.string().describe("Boxer"),
        fullname: zod.string().describe("Fullname"),
        updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
        createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
      }),
    )
    .describe("Boxers"),
});

export type BoxerListReplyData = zod.input<typeof BoxerListReplyData>;
export type BoxerListReplyDataOutput = zod.output<typeof BoxerListReplyData>;
