/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerControllerHandleBoxerCreateBody = zod.object({
  data: zod.object({
    boxer: zod.object({
      fullname: zod.string(),
    }),
  }),
});

export type BoxerControllerHandleBoxerCreateBody = zod.input<
  typeof BoxerControllerHandleBoxerCreateBody
>;
export type BoxerControllerHandleBoxerCreateBodyOutput = zod.output<
  typeof BoxerControllerHandleBoxerCreateBody
>;
