/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerUpdateSchemaData = zod.object({
  boxer: zod
    .object({
      fullname: zod.string().optional().describe("Fullname"),
    })
    .describe("Boxer"),
});

export type BoxerUpdateSchemaData = zod.input<typeof BoxerUpdateSchemaData>;
export type BoxerUpdateSchemaDataOutput = zod.output<
  typeof BoxerUpdateSchemaData
>;
