/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerIdUpdateSchema = zod.object({
  data: zod
    .object({
      boxer: zod
        .object({
          fullname: zod.string().optional().describe("Fullname"),
        })
        .describe("Boxer"),
    })
    .describe("Data"),
});

export type BoxerIdUpdateSchema = zod.input<typeof BoxerIdUpdateSchema>;
export type BoxerIdUpdateSchemaOutput = zod.output<typeof BoxerIdUpdateSchema>;
