/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerCreateRequestDataBoxerSchema = zod.object({
  fullname: zod.string(),
});

export type BoxerCreateRequestDataBoxerSchema = zod.input<
  typeof BoxerCreateRequestDataBoxerSchema
>;
export type BoxerCreateRequestDataBoxerSchemaOutput = zod.output<
  typeof BoxerCreateRequestDataBoxerSchema
>;
