/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerListReply = zod.object({
  data: zod
    .object({
      boxers: zod
        .array(
          zod.object({
            boxerId: zod.string().describe("Boxer"),
            fullname: zod.string().describe("Fullname"),
            updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
            createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
          }),
        )
        .describe("Boxers"),
    })
    .describe("Data"),
  meta: zod
    .object({
      count: zod.number().describe("Count"),
    })
    .describe("Meta"),
});

export type BoxerListReply = zod.input<typeof BoxerListReply>;
export type BoxerListReplyOutput = zod.output<typeof BoxerListReply>;
