/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerIdUpdateSchemaDataBoxer = zod.object({
  fullname: zod.string().optional().describe("Fullname"),
});

export type BoxerIdUpdateSchemaDataBoxer = zod.input<
  typeof BoxerIdUpdateSchemaDataBoxer
>;
export type BoxerIdUpdateSchemaDataBoxerOutput = zod.output<
  typeof BoxerIdUpdateSchemaDataBoxer
>;
