/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerCreateSchemaDataBoxer = zod.object({
  fullname: zod.string().describe("Fullname"),
});

export type BoxerCreateSchemaDataBoxer = zod.input<
  typeof BoxerCreateSchemaDataBoxer
>;
export type BoxerCreateSchemaDataBoxerOutput = zod.output<
  typeof BoxerCreateSchemaDataBoxer
>;
