/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerListResponseDataSchema = zod.object({
  boxers: zod.array(
    zod.object({
      boxerId: zod.string(),
      fullname: zod.string(),
      updatedAt: zod.iso.datetime({ offset: true }),
      createdAt: zod.iso.datetime({ offset: true }),
    }),
  ),
});

export type BoxerListResponseDataSchema = zod.input<
  typeof BoxerListResponseDataSchema
>;
export type BoxerListResponseDataSchemaOutput = zod.output<
  typeof BoxerListResponseDataSchema
>;
