/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerUpdateRequestDataSchema = zod.object({
  boxer: zod.object({
    fullname: zod.string().optional(),
  }),
});

export type BoxerUpdateRequestDataSchema = zod.input<
  typeof BoxerUpdateRequestDataSchema
>;
export type BoxerUpdateRequestDataSchemaOutput = zod.output<
  typeof BoxerUpdateRequestDataSchema
>;
