/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerUpdateSchemaDataBoxer = zod.object({
  fullname: zod.string().optional().describe("Fullname"),
});

export type BoxerUpdateSchemaDataBoxer = zod.input<
  typeof BoxerUpdateSchemaDataBoxer
>;
export type BoxerUpdateSchemaDataBoxerOutput = zod.output<
  typeof BoxerUpdateSchemaDataBoxer
>;
