/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerCreateRequestDataSchema = zod.object({
  boxer: zod.object({
    fullname: zod.string(),
  }),
});

export type BoxerCreateRequestDataSchema = zod.input<
  typeof BoxerCreateRequestDataSchema
>;
export type BoxerCreateRequestDataSchemaOutput = zod.output<
  typeof BoxerCreateRequestDataSchema
>;
