/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerCreateSchemaData = zod.object({
  boxer: zod
    .object({
      fullname: zod.string().describe("Fullname"),
    })
    .describe("Boxer"),
});

export type BoxerCreateSchemaData = zod.input<typeof BoxerCreateSchemaData>;
export type BoxerCreateSchemaDataOutput = zod.output<
  typeof BoxerCreateSchemaData
>;
