/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerUpdateResponseSchema = zod.object({
  data: zod.object({
    boxer: zod.object({
      boxerId: zod.string(),
      fullname: zod.string(),
      updatedAt: zod.iso.datetime({ offset: true }),
      createdAt: zod.iso.datetime({ offset: true }),
    }),
  }),
});

export type BoxerUpdateResponseSchema = zod.input<
  typeof BoxerUpdateResponseSchema
>;
export type BoxerUpdateResponseSchemaOutput = zod.output<
  typeof BoxerUpdateResponseSchema
>;
