/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerInfoReplyData = zod.object({
  boxer: zod
    .object({
      boxerId: zod.string().describe("Boxer"),
      fullname: zod.string().describe("Fullname"),
      updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
      createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
    })
    .describe("Boxer"),
});

export type BoxerInfoReplyData = zod.input<typeof BoxerInfoReplyData>;
export type BoxerInfoReplyDataOutput = zod.output<typeof BoxerInfoReplyData>;
