/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerUpdateSchema = zod.object({
  data: zod
    .object({
      boxer: zod
        .object({
          fullname: zod.string().optional().describe("Fullname"),
        })
        .describe("Boxer"),
    })
    .describe("Data"),
});

export type BoxerUpdateSchema = zod.input<typeof BoxerUpdateSchema>;
export type BoxerUpdateSchemaOutput = zod.output<typeof BoxerUpdateSchema>;
