/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerIdUpdateSchemaData = zod.object({
  boxer: zod
    .object({
      fullname: zod.string().optional().describe("Fullname"),
    })
    .describe("Boxer"),
});

export type BoxerIdUpdateSchemaData = zod.input<typeof BoxerIdUpdateSchemaData>;
export type BoxerIdUpdateSchemaDataOutput = zod.output<
  typeof BoxerIdUpdateSchemaData
>;
