/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerListReplyDataBoxer = zod.object({
  boxerId: zod.string().describe("Boxer"),
  fullname: zod.string().describe("Fullname"),
  updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
  createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
});

export type BoxerListReplyDataBoxer = zod.input<typeof BoxerListReplyDataBoxer>;
export type BoxerListReplyDataBoxerOutput = zod.output<
  typeof BoxerListReplyDataBoxer
>;
