/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerListResponseDataBoxerSchema = zod.object({
  boxerId: zod.string(),
  fullname: zod.string(),
  updatedAt: zod.iso.datetime({ offset: true }),
  createdAt: zod.iso.datetime({ offset: true }),
});

export type BoxerListResponseDataBoxerSchema = zod.input<
  typeof BoxerListResponseDataBoxerSchema
>;
export type BoxerListResponseDataBoxerSchemaOutput = zod.output<
  typeof BoxerListResponseDataBoxerSchema
>;
