/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerControllerHandleBoxerUpdateBody = zod.object({
  data: zod.object({
    boxer: zod.object({
      fullname: zod.string().optional(),
    }),
  }),
});

export type BoxerControllerHandleBoxerUpdateBody = zod.input<
  typeof BoxerControllerHandleBoxerUpdateBody
>;
export type BoxerControllerHandleBoxerUpdateBodyOutput = zod.output<
  typeof BoxerControllerHandleBoxerUpdateBody
>;
