/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const BoxerUpdateRequestDataBoxerSchema = zod.object({
  fullname: zod.string().optional(),
});

export type BoxerUpdateRequestDataBoxerSchema = zod.input<
  typeof BoxerUpdateRequestDataBoxerSchema
>;
export type BoxerUpdateRequestDataBoxerSchemaOutput = zod.output<
  typeof BoxerUpdateRequestDataBoxerSchema
>;
