/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EventCreateSchemaMeta = zod.object({
  blue: zod
    .object({
      boxerId: zod.string().describe("Boxer"),
    })
    .describe("Blue"),
  red: zod
    .object({
      boxerId: zod.string().describe("Boxer"),
    })
    .describe("Red"),
});

export type EventCreateSchemaMeta = zod.input<typeof EventCreateSchemaMeta>;
export type EventCreateSchemaMetaOutput = zod.output<
  typeof EventCreateSchemaMeta
>;
