/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EventCreateSchemaDataEvent = zod.object({
  tournamentId: zod.string().describe("Tournament"),
  venueId: zod.string().describe("Venue"),
  blueId: zod.string().describe("Blue"),
  redId: zod.string().describe("Red"),
  schedule: zod.iso.datetime({ offset: true }).describe("Schedule"),
  mode: zod.enum(["UNKNOWN", "MANUAL", "AUTO"]).describe("Mode"),
});

export type EventCreateSchemaDataEvent = zod.input<
  typeof EventCreateSchemaDataEvent
>;
export type EventCreateSchemaDataEventOutput = zod.output<
  typeof EventCreateSchemaDataEvent
>;
