/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EventCreateSchema = zod
  .object({
    data: zod
      .object({
        event: zod
          .object({
            tournamentId: zod.string(),
            venueId: zod.string(),
            blueId: zod.string(),
            redId: zod.string(),
            schedule: zod.iso.datetime({ offset: true }),
            mode: zod.enum(["UNKNOWN", "MANUAL", "AUTO"]),
          })
          .describe("Event"),
      })
      .describe("Data"),
  })
  .describe("Create");

export type EventCreateSchema = zod.input<typeof EventCreateSchema>;
export type EventCreateSchemaOutput = zod.output<typeof EventCreateSchema>;
