/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EventIdInfoReplyDataEvent = zod.object({
  eventId: zod.string().describe("Event"),
  tournamentId: zod.string().describe("Tournament"),
  venueId: zod.string().describe("Venue"),
  schedule: zod.iso.datetime({ offset: true }).describe("Schedule"),
  status: zod
    .enum(["SCHEDULED", "CANCELLED", "FINISHED", "UNKNOWN", "STARTED"])
    .describe("Status"),
  mode: zod.enum(["UNKNOWN", "MANUAL", "AUTO"]).describe("Mode"),
  url: zod.string().describe("Url"),
  key: zod.string().describe("Key"),
  updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
  createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
});

export type EventIdInfoReplyDataEvent = zod.input<
  typeof EventIdInfoReplyDataEvent
>;
export type EventIdInfoReplyDataEventOutput = zod.output<
  typeof EventIdInfoReplyDataEvent
>;
