/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EventControllerHandleEventListParams = zod.object({
  contains: zod.string().optional(),
  order: zod.enum(["asc", "desc"]).optional(),
  skip: zod.number(),
  take: zod.number(),
  by: zod.string().optional(),
});

export type EventControllerHandleEventListParams = zod.input<
  typeof EventControllerHandleEventListParams
>;
export type EventControllerHandleEventListParamsOutput = zod.output<
  typeof EventControllerHandleEventListParams
>;
