/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EventUpdateReplyDataEvent = zod.object({
  eventId: zod.string().describe("Event"),
  tournamentId: zod.string().describe("Tournament"),
  venueId: zod.string().describe("Venue"),
  schedule: zod.iso.datetime({ offset: true }).describe("Schedule"),
  status: zod
    .enum(["SCHEDULED", "CANCELLED", "FINISHED", "UNKNOWN", "STARTED"])
    .describe("Status"),
  title: zod.string().describe("Title"),
  mode: zod.enum(["UNKNOWN", "MANUAL", "AUTO"]).describe("Mode"),
  key: zod.string().describe("Key"),
  updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
  createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
});

export type EventUpdateReplyDataEvent = zod.input<
  typeof EventUpdateReplyDataEvent
>;
export type EventUpdateReplyDataEventOutput = zod.output<
  typeof EventUpdateReplyDataEvent
>;
