/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EventUpdateDataEventSchema = zod
  .object({
    schedule: zod.iso.datetime({ offset: true }).optional(),
    title: zod.string().optional(),
    mode: zod.enum(["UNKNOWN", "MANUAL", "AUTO"]).optional(),
  })
  .describe("Event");

export type EventUpdateDataEventSchema = zod.input<
  typeof EventUpdateDataEventSchema
>;
export type EventUpdateDataEventSchemaOutput = zod.output<
  typeof EventUpdateDataEventSchema
>;
