/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EventUpdateRequestDataEventSchema = zod.object({
  schedule: zod.iso.datetime({ offset: true }).optional(),
  title: zod.string().optional(),
  mode: zod.enum(["UNKNOWN", "MANUAL", "AUTO"]).optional(),
});

export type EventUpdateRequestDataEventSchema = zod.input<
  typeof EventUpdateRequestDataEventSchema
>;
export type EventUpdateRequestDataEventSchemaOutput = zod.output<
  typeof EventUpdateRequestDataEventSchema
>;
