/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EventIdInfoReply = zod.object({
  data: zod
    .object({
      event: zod
        .object({
          eventId: zod.string().describe("Event"),
          tournamentId: zod.string().describe("Tournament"),
          venueId: zod.string().describe("Venue"),
          schedule: zod.iso.datetime({ offset: true }).describe("Schedule"),
          status: zod
            .enum(["SCHEDULED", "CANCELLED", "FINISHED", "UNKNOWN", "STARTED"])
            .describe("Status"),
          mode: zod.enum(["UNKNOWN", "MANUAL", "AUTO"]).describe("Mode"),
          url: zod.string().describe("Url"),
          key: zod.string().describe("Key"),
          updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
          createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
        })
        .describe("Event"),
    })
    .describe("Data"),
  meta: zod
    .object({
      url: zod.string().describe("Url"),
    })
    .describe("Meta"),
});

export type EventIdInfoReply = zod.input<typeof EventIdInfoReply>;
export type EventIdInfoReplyOutput = zod.output<typeof EventIdInfoReply>;
