/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EventCreateSchema = zod.object({
  data: zod
    .object({
      event: zod
        .object({
          tournamentId: zod.string().describe("Tournament"),
          venueId: zod.string().describe("Venue"),
          schedule: zod.iso.datetime({ offset: true }).describe("Schedule"),
          mode: zod.enum(["UNKNOWN", "MANUAL", "AUTO"]).describe("Mode"),
        })
        .describe("Event"),
    })
    .describe("Data"),
  meta: zod
    .object({
      blue: zod
        .object({
          boxerId: zod.string().describe("Boxer"),
        })
        .describe("Blue"),
      red: zod
        .object({
          boxerId: zod.string().describe("Boxer"),
        })
        .describe("Red"),
    })
    .describe("Meta"),
});

export type EventCreateSchema = zod.input<typeof EventCreateSchema>;
export type EventCreateSchemaOutput = zod.output<typeof EventCreateSchema>;
