/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EventCreateSchemaMetaEntry = zod.object({
  boxerId: zod.string().describe("Boxer"),
});

export type EventCreateSchemaMetaEntry = zod.input<
  typeof EventCreateSchemaMetaEntry
>;
export type EventCreateSchemaMetaEntryOutput = zod.output<
  typeof EventCreateSchemaMetaEntry
>;
