/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EventUpdateRequestDataSchema = zod.object({
  event: zod.object({
    schedule: zod.iso.datetime({ offset: true }).optional(),
    title: zod.string().optional(),
    mode: zod.enum(["UNKNOWN", "MANUAL", "AUTO"]).optional(),
  }),
});

export type EventUpdateRequestDataSchema = zod.input<
  typeof EventUpdateRequestDataSchema
>;
export type EventUpdateRequestDataSchemaOutput = zod.output<
  typeof EventUpdateRequestDataSchema
>;
