/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EventIdUpdateSchemaDataEvent = zod.object({
  tournamentId: zod.string().optional().describe("Tournament"),
  venueId: zod.string().optional().describe("Venue"),
  schedule: zod.iso.datetime({ offset: true }).optional().describe("Schedule"),
  mode: zod.enum(["UNKNOWN", "MANUAL", "AUTO"]).optional().describe("Mode"),
});

export type EventIdUpdateSchemaDataEvent = zod.input<
  typeof EventIdUpdateSchemaDataEvent
>;
export type EventIdUpdateSchemaDataEventOutput = zod.output<
  typeof EventIdUpdateSchemaDataEvent
>;
