/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EventIdInfoReplyMeta = zod.object({
  url: zod.string().describe("Url"),
});

export type EventIdInfoReplyMeta = zod.input<typeof EventIdInfoReplyMeta>;
export type EventIdInfoReplyMetaOutput = zod.output<
  typeof EventIdInfoReplyMeta
>;
