/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EventUpdateSchemaDataEvent = zod.object({
  schedule: zod.iso.datetime({ offset: true }).optional().describe("Schedule"),
  title: zod.string().optional().describe("Title"),
  mode: zod.enum(["UNKNOWN", "MANUAL", "AUTO"]).optional().describe("Mode"),
});

export type EventUpdateSchemaDataEvent = zod.input<
  typeof EventUpdateSchemaDataEvent
>;
export type EventUpdateSchemaDataEventOutput = zod.output<
  typeof EventUpdateSchemaDataEvent
>;
