/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EventListReplyData = zod.object({
  events: zod
    .array(
      zod.object({
        eventId: zod.string().describe("Event"),
        tournamentId: zod.string().describe("Tournament"),
        venueId: zod.string().describe("Venue"),
        schedule: zod.iso.datetime({ offset: true }).describe("Schedule"),
        status: zod
          .enum(["SCHEDULED", "CANCELLED", "FINISHED", "UNKNOWN", "STARTED"])
          .describe("Status"),
        mode: zod.enum(["UNKNOWN", "MANUAL", "AUTO"]).describe("Mode"),
        url: zod.string().describe("Url"),
        key: zod.string().describe("Key"),
        updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
        createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
      }),
    )
    .describe("Events"),
});

export type EventListReplyData = zod.input<typeof EventListReplyData>;
export type EventListReplyDataOutput = zod.output<typeof EventListReplyData>;
