/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EventCreateResponseDataSchema = zod.object({
  event: zod.object({
    eventId: zod.string(),
    tournamentId: zod.string(),
    venueId: zod.string(),
    schedule: zod.iso.datetime({ offset: true }),
    status: zod.enum([
      "SCHEDULED",
      "CANCELLED",
      "FINISHED",
      "UNKNOWN",
      "STARTED",
    ]),
    title: zod.string(),
    mode: zod.enum(["UNKNOWN", "MANUAL", "AUTO"]),
    key: zod.string(),
    updatedAt: zod.iso.datetime({ offset: true }),
    createdAt: zod.iso.datetime({ offset: true }),
  }),
});

export type EventCreateResponseDataSchema = zod.input<
  typeof EventCreateResponseDataSchema
>;
export type EventCreateResponseDataSchemaOutput = zod.output<
  typeof EventCreateResponseDataSchema
>;
