/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EventListResponseDataSchema = zod.object({
  events: zod.array(
    zod.object({
      eventId: zod.string(),
      tournamentId: zod.string(),
      venueId: zod.string(),
      schedule: zod.iso.datetime({ offset: true }),
      status: zod.enum([
        "SCHEDULED",
        "CANCELLED",
        "FINISHED",
        "UNKNOWN",
        "STARTED",
      ]),
      title: zod.string(),
      mode: zod.enum(["UNKNOWN", "MANUAL", "AUTO"]),
      key: zod.string(),
      updatedAt: zod.iso.datetime({ offset: true }),
      createdAt: zod.iso.datetime({ offset: true }),
    }),
  ),
});

export type EventListResponseDataSchema = zod.input<
  typeof EventListResponseDataSchema
>;
export type EventListResponseDataSchemaOutput = zod.output<
  typeof EventListResponseDataSchema
>;
