/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const EventListReplyMeta = zod.object({
  count: zod.number().describe("Count"),
});

export type EventListReplyMeta = zod.input<typeof EventListReplyMeta>;
export type EventListReplyMetaOutput = zod.output<typeof EventListReplyMeta>;
