/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const GetTournamentListParams = zod.object({
  contains: zod.string().optional(),
  order: zod.enum(["asc", "desc"]).optional(),
  skip: zod.number().optional(),
  take: zod.number().optional(),
  by: zod.string().optional(),
});

export type GetTournamentListParams = zod.input<typeof GetTournamentListParams>;
export type GetTournamentListParamsOutput = zod.output<
  typeof GetTournamentListParams
>;
