/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const HealthCheckReplyMeta = zod.object({
  message: zod.string().describe("Message"),
});

export type HealthCheckReplyMeta = zod.input<typeof HealthCheckReplyMeta>;
export type HealthCheckReplyMetaOutput = zod.output<
  typeof HealthCheckReplyMeta
>;
