/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const HealthCheckReply = zod.object({
  meta: zod
    .object({
      message: zod.string().describe("Message"),
    })
    .describe("Meta"),
});

export type HealthCheckReply = zod.input<typeof HealthCheckReply>;
export type HealthCheckReplyOutput = zod.output<typeof HealthCheckReply>;
