/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ManagerUpdateSchemaDataManager = zod.object({
  fullname: zod.string().optional().describe("Fullname"),
  username: zod.string().optional().describe("Username"),
  password: zod.string().optional().describe("Password"),
});

export type ManagerUpdateSchemaDataManager = zod.input<
  typeof ManagerUpdateSchemaDataManager
>;
export type ManagerUpdateSchemaDataManagerOutput = zod.output<
  typeof ManagerUpdateSchemaDataManager
>;
