/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ManagerListReplyMeta = zod.object({
  count: zod.number().describe("Count"),
});

export type ManagerListReplyMeta = zod.input<typeof ManagerListReplyMeta>;
export type ManagerListReplyMetaOutput = zod.output<
  typeof ManagerListReplyMeta
>;
