/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ManagerUpdateSchemaData = zod.object({
  manager: zod
    .object({
      fullname: zod.string().optional().describe("Fullname"),
      username: zod.string().optional().describe("Username"),
      password: zod.string().optional().describe("Password"),
    })
    .describe("Manager"),
});

export type ManagerUpdateSchemaData = zod.input<typeof ManagerUpdateSchemaData>;
export type ManagerUpdateSchemaDataOutput = zod.output<
  typeof ManagerUpdateSchemaData
>;
