/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ManagerCreateSchemaDataManager = zod.object({
  fullname: zod.string().describe("Fullname"),
  username: zod.string().describe("Username"),
  password: zod.string().describe("Password"),
  role: zod
    .enum(["OPERATOR", "UNKNOWN", "MANAGER", "JUDGE", "ROOT"])
    .describe("Role"),
});

export type ManagerCreateSchemaDataManager = zod.input<
  typeof ManagerCreateSchemaDataManager
>;
export type ManagerCreateSchemaDataManagerOutput = zod.output<
  typeof ManagerCreateSchemaDataManager
>;
