/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ManagerIdUpdateSchemaDataManager = zod.object({
  fullname: zod.string().optional().describe("Fullname"),
  username: zod.string().optional().describe("Username"),
  password: zod.string().optional().describe("Password"),
  role: zod
    .enum(["OPERATOR", "UNKNOWN", "MANAGER", "JUDGE", "ROOT"])
    .optional()
    .describe("Role"),
});

export type ManagerIdUpdateSchemaDataManager = zod.input<
  typeof ManagerIdUpdateSchemaDataManager
>;
export type ManagerIdUpdateSchemaDataManagerOutput = zod.output<
  typeof ManagerIdUpdateSchemaDataManager
>;
