/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ManagerInfoReply = zod.object({
  data: zod
    .object({
      manager: zod
        .object({
          managerId: zod.string().describe("Manager"),
          fullname: zod.string().describe("Fullname"),
          username: zod.string().describe("Username"),
          role: zod
            .enum(["OPERATOR", "UNKNOWN", "MANAGER", "JUDGE", "ROOT"])
            .describe("Role"),
          updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
          createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
        })
        .describe("Manager"),
    })
    .describe("Data"),
});

export type ManagerInfoReply = zod.input<typeof ManagerInfoReply>;
export type ManagerInfoReplyOutput = zod.output<typeof ManagerInfoReply>;
