/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ManagerAuthReplyMeta = zod.object({
  jwt: zod.string().describe("Jwt"),
});

export type ManagerAuthReplyMeta = zod.input<typeof ManagerAuthReplyMeta>;
export type ManagerAuthReplyMetaOutput = zod.output<
  typeof ManagerAuthReplyMeta
>;
