/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ManagerControllerHandleManagerIdUpdateBody = zod.object({
  data: zod
    .object({
      manager: zod
        .object({
          fullname: zod.string().optional().describe("Fullname"),
          username: zod.string().optional().describe("Username"),
          password: zod.string().optional().describe("Password"),
          role: zod
            .enum(["OPERATOR", "UNKNOWN", "MANAGER", "JUDGE", "ROOT"])
            .optional()
            .describe("Role"),
        })
        .describe("Manager"),
    })
    .describe("Data"),
});

export type ManagerControllerHandleManagerIdUpdateBody = zod.input<
  typeof ManagerControllerHandleManagerIdUpdateBody
>;
export type ManagerControllerHandleManagerIdUpdateBodyOutput = zod.output<
  typeof ManagerControllerHandleManagerIdUpdateBody
>;
