/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ManagerAuthSchema = zod.object({
  data: zod
    .object({
      manager: zod
        .object({
          username: zod.string().describe("Username"),
          password: zod.string().describe("Password"),
        })
        .describe("Manager"),
    })
    .describe("Data"),
});

export type ManagerAuthSchema = zod.input<typeof ManagerAuthSchema>;
export type ManagerAuthSchemaOutput = zod.output<typeof ManagerAuthSchema>;
