/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ManagerCreateSchemaData = zod.object({
  manager: zod
    .object({
      fullname: zod.string().describe("Fullname"),
      username: zod.string().describe("Username"),
      password: zod.string().describe("Password"),
      role: zod
        .enum(["OPERATOR", "UNKNOWN", "MANAGER", "JUDGE", "ROOT"])
        .describe("Role"),
    })
    .describe("Manager"),
});

export type ManagerCreateSchemaData = zod.input<typeof ManagerCreateSchemaData>;
export type ManagerCreateSchemaDataOutput = zod.output<
  typeof ManagerCreateSchemaData
>;
