/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ManagerAuthSchemaDataManager = zod.object({
  username: zod.string().describe("Username"),
  password: zod.string().describe("Password"),
});

export type ManagerAuthSchemaDataManager = zod.input<
  typeof ManagerAuthSchemaDataManager
>;
export type ManagerAuthSchemaDataManagerOutput = zod.output<
  typeof ManagerAuthSchemaDataManager
>;
