/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ManagerControllerHandleManagerAuthBody = zod.object({
  data: zod
    .object({
      manager: zod
        .object({
          username: zod.string().describe("Username"),
          password: zod.string().describe("Password"),
        })
        .describe("Manager"),
    })
    .describe("Data"),
});

export type ManagerControllerHandleManagerAuthBody = zod.input<
  typeof ManagerControllerHandleManagerAuthBody
>;
export type ManagerControllerHandleManagerAuthBodyOutput = zod.output<
  typeof ManagerControllerHandleManagerAuthBody
>;
