/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ManagerInfoReplyData = zod.object({
  manager: zod
    .object({
      managerId: zod.string().describe("Manager"),
      fullname: zod.string().describe("Fullname"),
      username: zod.string().describe("Username"),
      role: zod
        .enum(["OPERATOR", "UNKNOWN", "MANAGER", "JUDGE", "ROOT"])
        .describe("Role"),
      updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
      createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
    })
    .describe("Manager"),
});

export type ManagerInfoReplyData = zod.input<typeof ManagerInfoReplyData>;
export type ManagerInfoReplyDataOutput = zod.output<
  typeof ManagerInfoReplyData
>;
