/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ManagerAuthSchemaData = zod.object({
  manager: zod
    .object({
      username: zod.string().describe("Username"),
      password: zod.string().describe("Password"),
    })
    .describe("Manager"),
});

export type ManagerAuthSchemaData = zod.input<typeof ManagerAuthSchemaData>;
export type ManagerAuthSchemaDataOutput = zod.output<
  typeof ManagerAuthSchemaData
>;
