/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ManagerIdUpdateSchemaData = zod.object({
  manager: zod
    .object({
      fullname: zod.string().optional().describe("Fullname"),
      username: zod.string().optional().describe("Username"),
      password: zod.string().optional().describe("Password"),
      role: zod
        .enum(["OPERATOR", "UNKNOWN", "MANAGER", "JUDGE", "ROOT"])
        .optional()
        .describe("Role"),
    })
    .describe("Manager"),
});

export type ManagerIdUpdateSchemaData = zod.input<
  typeof ManagerIdUpdateSchemaData
>;
export type ManagerIdUpdateSchemaDataOutput = zod.output<
  typeof ManagerIdUpdateSchemaData
>;
