/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ManagerListReplyDataManager = zod.object({
  managerId: zod.string().describe("Manager"),
  fullname: zod.string().describe("Fullname"),
  username: zod.string().describe("Username"),
  role: zod
    .enum(["OPERATOR", "UNKNOWN", "MANAGER", "JUDGE", "ROOT"])
    .describe("Role"),
  updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
  createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
});

export type ManagerListReplyDataManager = zod.input<
  typeof ManagerListReplyDataManager
>;
export type ManagerListReplyDataManagerOutput = zod.output<
  typeof ManagerListReplyDataManager
>;
