/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const MatchIdInfoReply = zod.object({
  data: zod
    .object({
      match: zod
        .object({
          matchId: zod.string().describe("Match"),
          eventId: zod.string().describe("Event"),
          status: zod
            .enum(["SCHEDULED", "CANCELLED", "FINISHED", "UNKNOWN", "STARTED"])
            .describe("Status"),
          winner: zod
            .enum(["UNKNOWN", "BLUE", "DRAW", "RED"])
            .describe("Winner"),
          number: zod.number().describe("Number"),
          updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
          createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
        })
        .describe("Match"),
    })
    .describe("Data"),
});

export type MatchIdInfoReply = zod.input<typeof MatchIdInfoReply>;
export type MatchIdInfoReplyOutput = zod.output<typeof MatchIdInfoReply>;
