/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const MatchControllerHandleMatchListParams = zod.object({
  contains: zod.string().optional(),
  order: zod.enum(["asc", "desc"]).optional(),
  skip: zod.number(),
  take: zod.number(),
  by: zod.string().optional(),
});

export type MatchControllerHandleMatchListParams = zod.input<
  typeof MatchControllerHandleMatchListParams
>;
export type MatchControllerHandleMatchListParamsOutput = zod.output<
  typeof MatchControllerHandleMatchListParams
>;
