/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const OverlayUpdateSchemaDataOverlay = zod.object({
  title: zod.string().optional().describe("Title"),
  url: zod.string().optional().describe("Url"),
});

export type OverlayUpdateSchemaDataOverlay = zod.input<
  typeof OverlayUpdateSchemaDataOverlay
>;
export type OverlayUpdateSchemaDataOverlayOutput = zod.output<
  typeof OverlayUpdateSchemaDataOverlay
>;
