/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const OverlayListReply = zod.object({
  data: zod
    .object({
      overlays: zod
        .array(
          zod.object({
            overlayId: zod.string().describe("Overlay"),
            title: zod.string().describe("Title"),
            url: zod.string().describe("Url"),
            updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
            createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
          }),
        )
        .describe("Overlays"),
    })
    .describe("Data"),
  meta: zod
    .object({
      count: zod.number().describe("Count"),
    })
    .describe("Meta"),
});

export type OverlayListReply = zod.input<typeof OverlayListReply>;
export type OverlayListReplyOutput = zod.output<typeof OverlayListReply>;
