/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const OverlayCreateSchema = zod.object({
  data: zod
    .object({
      overlay: zod
        .object({
          title: zod.string().describe("Title"),
          url: zod.string().describe("Url"),
        })
        .describe("Overlay"),
    })
    .describe("Data"),
});

export type OverlayCreateSchema = zod.input<typeof OverlayCreateSchema>;
export type OverlayCreateSchemaOutput = zod.output<typeof OverlayCreateSchema>;
