/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const OverlayIdUpdateSchemaData = zod.object({
  overlay: zod
    .object({
      title: zod.string().optional().describe("Title"),
      url: zod.string().optional().describe("Url"),
    })
    .describe("Overlay"),
});

export type OverlayIdUpdateSchemaData = zod.input<
  typeof OverlayIdUpdateSchemaData
>;
export type OverlayIdUpdateSchemaDataOutput = zod.output<
  typeof OverlayIdUpdateSchemaData
>;
