/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const OverlayControllerHandleOverlayIdUpdateBody = zod.object({
  data: zod
    .object({
      overlay: zod
        .object({
          title: zod.string().optional().describe("Title"),
          url: zod.string().optional().describe("Url"),
        })
        .describe("Overlay"),
    })
    .describe("Data"),
});

export type OverlayControllerHandleOverlayIdUpdateBody = zod.input<
  typeof OverlayControllerHandleOverlayIdUpdateBody
>;
export type OverlayControllerHandleOverlayIdUpdateBodyOutput = zod.output<
  typeof OverlayControllerHandleOverlayIdUpdateBody
>;
