/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const OverlayCreateSchemaData = zod.object({
  overlay: zod
    .object({
      title: zod.string().describe("Title"),
      url: zod.string().describe("Url"),
    })
    .describe("Overlay"),
});

export type OverlayCreateSchemaData = zod.input<typeof OverlayCreateSchemaData>;
export type OverlayCreateSchemaDataOutput = zod.output<
  typeof OverlayCreateSchemaData
>;
