/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const OverlayUpdateDataSchema = zod
  .object({
    overlay: zod
      .object({
        title: zod.string().optional(),
        url: zod.string().optional(),
      })
      .describe("Overlay"),
  })
  .describe("Data");

export type OverlayUpdateDataSchema = zod.input<typeof OverlayUpdateDataSchema>;
export type OverlayUpdateDataSchemaOutput = zod.output<
  typeof OverlayUpdateDataSchema
>;
