/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const OverlayCreateRequestDataOverlaySchema = zod.object({
  title: zod.string(),
  url: zod.string(),
});

export type OverlayCreateRequestDataOverlaySchema = zod.input<
  typeof OverlayCreateRequestDataOverlaySchema
>;
export type OverlayCreateRequestDataOverlaySchemaOutput = zod.output<
  typeof OverlayCreateRequestDataOverlaySchema
>;
