/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const OverlayControllerHandleOverlayCreateBody = zod.object({
  data: zod.object({
    overlay: zod.object({
      title: zod.string(),
      url: zod.string(),
    }),
  }),
});

export type OverlayControllerHandleOverlayCreateBody = zod.input<
  typeof OverlayControllerHandleOverlayCreateBody
>;
export type OverlayControllerHandleOverlayCreateBodyOutput = zod.output<
  typeof OverlayControllerHandleOverlayCreateBody
>;
