/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const OverlayUpdateSchemaData = zod.object({
  overlay: zod
    .object({
      title: zod.string().optional().describe("Title"),
      url: zod.string().optional().describe("Url"),
    })
    .describe("Overlay"),
});

export type OverlayUpdateSchemaData = zod.input<typeof OverlayUpdateSchemaData>;
export type OverlayUpdateSchemaDataOutput = zod.output<
  typeof OverlayUpdateSchemaData
>;
