/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const OverlayControllerHandleOverlayCreateBody = zod.object({
  data: zod
    .object({
      overlay: zod
        .object({
          title: zod.string().describe("Title"),
          url: zod.string().describe("Url"),
        })
        .describe("Overlay"),
    })
    .describe("Data"),
});

export type OverlayControllerHandleOverlayCreateBody = zod.input<
  typeof OverlayControllerHandleOverlayCreateBody
>;
export type OverlayControllerHandleOverlayCreateBodyOutput = zod.output<
  typeof OverlayControllerHandleOverlayCreateBody
>;
