/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const OverlayIdInfoReply = zod.object({
  data: zod
    .object({
      overlay: zod
        .object({
          overlayId: zod.string().describe("Overlay"),
          title: zod.string().describe("Title"),
          url: zod.string().describe("Url"),
          updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
          createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
        })
        .describe("Overlay"),
    })
    .describe("Data"),
});

export type OverlayIdInfoReply = zod.input<typeof OverlayIdInfoReply>;
export type OverlayIdInfoReplyOutput = zod.output<typeof OverlayIdInfoReply>;
