/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const OverlayIdUpdateSchemaDataOverlay = zod.object({
  title: zod.string().optional().describe("Title"),
  url: zod.string().optional().describe("Url"),
});

export type OverlayIdUpdateSchemaDataOverlay = zod.input<
  typeof OverlayIdUpdateSchemaDataOverlay
>;
export type OverlayIdUpdateSchemaDataOverlayOutput = zod.output<
  typeof OverlayIdUpdateSchemaDataOverlay
>;
