/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const OverlayUpdateSchema = zod
  .object({
    data: zod
      .object({
        overlay: zod
          .object({
            title: zod.string().optional(),
            url: zod.string().optional(),
          })
          .describe("Overlay"),
      })
      .describe("Data"),
  })
  .describe("Update");

export type OverlayUpdateSchema = zod.input<typeof OverlayUpdateSchema>;
export type OverlayUpdateSchemaOutput = zod.output<typeof OverlayUpdateSchema>;
