/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const OverlayControllerHandleOverlayUpdateBody = zod.object({
  data: zod.object({
    overlay: zod.object({
      title: zod.string().optional(),
      url: zod.string().optional(),
    }),
  }),
});

export type OverlayControllerHandleOverlayUpdateBody = zod.input<
  typeof OverlayControllerHandleOverlayUpdateBody
>;
export type OverlayControllerHandleOverlayUpdateBodyOutput = zod.output<
  typeof OverlayControllerHandleOverlayUpdateBody
>;
