/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const OverlayCreateDataSchema = zod
  .object({
    overlay: zod
      .object({
        title: zod.string(),
        url: zod.string(),
      })
      .describe("Overlay"),
  })
  .describe("Data");

export type OverlayCreateDataSchema = zod.input<typeof OverlayCreateDataSchema>;
export type OverlayCreateDataSchemaOutput = zod.output<
  typeof OverlayCreateDataSchema
>;
