/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const OverlayListReplyMeta = zod.object({
  count: zod.number().describe("Count"),
});

export type OverlayListReplyMeta = zod.input<typeof OverlayListReplyMeta>;
export type OverlayListReplyMetaOutput = zod.output<
  typeof OverlayListReplyMeta
>;
