/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const OverlayUpdateDataOverlaySchema = zod
  .object({
    title: zod.string().optional(),
    url: zod.string().optional(),
  })
  .describe("Overlay");

export type OverlayUpdateDataOverlaySchema = zod.input<
  typeof OverlayUpdateDataOverlaySchema
>;
export type OverlayUpdateDataOverlaySchemaOutput = zod.output<
  typeof OverlayUpdateDataOverlaySchema
>;
