/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const OverlayUpdateRequestDataOverlaySchema = zod.object({
  title: zod.string().optional(),
  url: zod.string().optional(),
});

export type OverlayUpdateRequestDataOverlaySchema = zod.input<
  typeof OverlayUpdateRequestDataOverlaySchema
>;
export type OverlayUpdateRequestDataOverlaySchemaOutput = zod.output<
  typeof OverlayUpdateRequestDataOverlaySchema
>;
