/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const PatchTerminalUpdateBody = zod.object({
  data: zod
    .object({
      terminal: zod
        .object({
          title: zod.string().optional().describe("Title"),
          url: zod.string().optional().describe("Url"),
        })
        .describe("Terminal"),
    })
    .describe("Data"),
});

export type PatchTerminalUpdateBody = zod.input<typeof PatchTerminalUpdateBody>;
export type PatchTerminalUpdateBodyOutput = zod.output<
  typeof PatchTerminalUpdateBody
>;
