/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const PatchOverlayUpdateBody = zod.object({
  data: zod
    .object({
      overlay: zod
        .object({
          title: zod.string().optional().describe("Title"),
          url: zod.string().optional().describe("Url"),
        })
        .describe("Overlay"),
    })
    .describe("Data"),
});

export type PatchOverlayUpdateBody = zod.input<typeof PatchOverlayUpdateBody>;
export type PatchOverlayUpdateBodyOutput = zod.output<
  typeof PatchOverlayUpdateBody
>;
