/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const PatchStreamUpdateBody = zod.object({
  data: zod
    .object({
      stream: zod
        .object({
          username: zod.string().optional().describe("Username"),
          password: zod.string().optional().describe("Password"),
          title: zod.string().optional().describe("Title"),
          http: zod.string().optional().describe("Http"),
          rtmp: zod.string().optional().describe("Rtmp"),
        })
        .describe("Stream"),
    })
    .describe("Data"),
});

export type PatchStreamUpdateBody = zod.input<typeof PatchStreamUpdateBody>;
export type PatchStreamUpdateBodyOutput = zod.output<
  typeof PatchStreamUpdateBody
>;
