/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const PatchVenueVenueIdUpdateBody = zod.object({
  data: zod
    .object({
      venue: zod
        .object({
          title: zod.string().optional().describe("Title"),
          key: zod.string().optional().describe("Key"),
        })
        .describe("Venue"),
    })
    .describe("Data"),
});

export type PatchVenueVenueIdUpdateBody = zod.input<
  typeof PatchVenueVenueIdUpdateBody
>;
export type PatchVenueVenueIdUpdateBodyOutput = zod.output<
  typeof PatchVenueVenueIdUpdateBody
>;
