/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const PostTournamentCreateBody = zod.object({
  data: zod
    .object({
      tournament: zod
        .object({
          timeout: zod.number().describe("Timeout"),
          title: zod.string().describe("Title"),
        })
        .describe("Tournament"),
    })
    .describe("Data"),
});

export type PostTournamentCreateBody = zod.input<
  typeof PostTournamentCreateBody
>;
export type PostTournamentCreateBodyOutput = zod.output<
  typeof PostTournamentCreateBody
>;
