/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ReportCreateSchemaData = zod.object({
  report: zod
    .object({
      tournamentId: zod.string().describe("Tournament"),
      from: zod.iso.datetime({ offset: true }).describe("From"),
      to: zod.iso.datetime({ offset: true }).describe("To"),
    })
    .describe("Report"),
});

export type ReportCreateSchemaData = zod.input<typeof ReportCreateSchemaData>;
export type ReportCreateSchemaDataOutput = zod.output<
  typeof ReportCreateSchemaData
>;
