/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ReportControllerHandleReportIdUploadBody = zod.object({
  file: zod.instanceof(File),
});

export type ReportControllerHandleReportIdUploadBody = zod.input<
  typeof ReportControllerHandleReportIdUploadBody
>;
export type ReportControllerHandleReportIdUploadBodyOutput = zod.output<
  typeof ReportControllerHandleReportIdUploadBody
>;
