/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ReportCreateSchema = zod.object({
  data: zod
    .object({
      report: zod
        .object({
          tournamentId: zod.string().describe("Tournament"),
          from: zod.iso.datetime({ offset: true }).describe("From"),
          to: zod.iso.datetime({ offset: true }).describe("To"),
        })
        .describe("Report"),
    })
    .describe("Data"),
});

export type ReportCreateSchema = zod.input<typeof ReportCreateSchema>;
export type ReportCreateSchemaOutput = zod.output<typeof ReportCreateSchema>;
