/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ReportCreateSchemaDataReport = zod.object({
  tournamentId: zod.string().describe("Tournament"),
  from: zod.iso.datetime({ offset: true }).describe("From"),
  to: zod.iso.datetime({ offset: true }).describe("To"),
});

export type ReportCreateSchemaDataReport = zod.input<
  typeof ReportCreateSchemaDataReport
>;
export type ReportCreateSchemaDataReportOutput = zod.output<
  typeof ReportCreateSchemaDataReport
>;
