/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ReportIdInfoReply = zod.object({
  data: zod
    .object({
      report: zod
        .object({
          tournamentId: zod.string().describe("Tournament"),
          reportId: zod.string().describe("Report"),
          filename: zod.string().describe("Filename"),
          mimetype: zod.string().describe("Mimetype"),
          from: zod.iso.datetime({ offset: true }).describe("From"),
          to: zod.iso.datetime({ offset: true }).describe("To"),
          updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
          createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
        })
        .describe("Report"),
    })
    .describe("Data"),
});

export type ReportIdInfoReply = zod.input<typeof ReportIdInfoReply>;
export type ReportIdInfoReplyOutput = zod.output<typeof ReportIdInfoReply>;
