/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const ReportIdUploadSchema = zod.object({
  file: zod.instanceof(File).describe("File"),
});

export type ReportIdUploadSchema = zod.input<typeof ReportIdUploadSchema>;
export type ReportIdUploadSchemaOutput = zod.output<
  typeof ReportIdUploadSchema
>;
