/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const RoundIdInfoReplyDataRound = zod.object({
  roundId: zod.string().describe("Round"),
  matchId: zod.string().describe("Match"),
  status: zod
    .enum(["SCHEDULED", "CANCELLED", "FINISHED", "UNKNOWN", "STARTED"])
    .describe("Status"),
  winner: zod.enum(["UNKNOWN", "BLUE", "DRAW", "RED"]).describe("Winner"),
  number: zod.number().describe("Number"),
  super: zod.enum(["UNKNOWN", "BLUE", "RED"]).describe("Super"),
  block: zod.enum(["UNKNOWN", "BLUE", "RED"]).describe("Block"),
  first: zod.enum(["UNKNOWN", "BLUE", "RED"]).describe("First"),
  last: zod
    .enum([
      "DAMAGEDOUBLE",
      "DAMAGEPLUS",
      "CROSSDOWN",
      "OVERHAND",
      "UPPERCUT",
      "HOOKDOWN",
      "SUPERHIT",
      "UNKNOWN",
      "CROSSUP",
      "JABDOWN",
      "HOOKUP",
      "JABUP",
      "NOHIT",
    ])
    .describe("Last"),
  updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
  createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
});

export type RoundIdInfoReplyDataRound = zod.input<
  typeof RoundIdInfoReplyDataRound
>;
export type RoundIdInfoReplyDataRoundOutput = zod.output<
  typeof RoundIdInfoReplyDataRound
>;
