/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StationListReplyMeta = zod.object({
  count: zod.number().describe("Count"),
});

export type StationListReplyMeta = zod.input<typeof StationListReplyMeta>;
export type StationListReplyMetaOutput = zod.output<
  typeof StationListReplyMeta
>;
