/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StationIdUpdateSchemaData = zod.object({
  station: zod
    .object({
      title: zod.string().optional().describe("Title"),
      url: zod.string().optional().describe("Url"),
    })
    .describe("Station"),
});

export type StationIdUpdateSchemaData = zod.input<
  typeof StationIdUpdateSchemaData
>;
export type StationIdUpdateSchemaDataOutput = zod.output<
  typeof StationIdUpdateSchemaData
>;
