/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StationListReplyDataStation = zod.object({
  stationId: zod.string().describe("Station"),
  title: zod.string().describe("Title"),
  url: zod.string().describe("Url"),
  updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
  createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
});

export type StationListReplyDataStation = zod.input<
  typeof StationListReplyDataStation
>;
export type StationListReplyDataStationOutput = zod.output<
  typeof StationListReplyDataStation
>;
