/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StationCreateSchemaDataStation = zod.object({
  title: zod.string().describe("Title"),
  url: zod.string().describe("Url"),
});

export type StationCreateSchemaDataStation = zod.input<
  typeof StationCreateSchemaDataStation
>;
export type StationCreateSchemaDataStationOutput = zod.output<
  typeof StationCreateSchemaDataStation
>;
