/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StationControllerHandleStationCreateBody = zod.object({
  data: zod
    .object({
      station: zod
        .object({
          title: zod.string().describe("Title"),
          url: zod.string().describe("Url"),
        })
        .describe("Station"),
    })
    .describe("Data"),
});

export type StationControllerHandleStationCreateBody = zod.input<
  typeof StationControllerHandleStationCreateBody
>;
export type StationControllerHandleStationCreateBodyOutput = zod.output<
  typeof StationControllerHandleStationCreateBody
>;
