/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StationCreateSchemaData = zod.object({
  station: zod
    .object({
      title: zod.string().describe("Title"),
      url: zod.string().describe("Url"),
    })
    .describe("Station"),
});

export type StationCreateSchemaData = zod.input<typeof StationCreateSchemaData>;
export type StationCreateSchemaDataOutput = zod.output<
  typeof StationCreateSchemaData
>;
