/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StationIdUpdateSchema = zod.object({
  data: zod
    .object({
      station: zod
        .object({
          title: zod.string().optional().describe("Title"),
          url: zod.string().optional().describe("Url"),
        })
        .describe("Station"),
    })
    .describe("Data"),
});

export type StationIdUpdateSchema = zod.input<typeof StationIdUpdateSchema>;
export type StationIdUpdateSchemaOutput = zod.output<
  typeof StationIdUpdateSchema
>;
