/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StationListReply = zod.object({
  data: zod
    .object({
      stations: zod
        .array(
          zod.object({
            stationId: zod.string().describe("Station"),
            title: zod.string().describe("Title"),
            url: zod.string().describe("Url"),
            updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
            createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
          }),
        )
        .describe("Stations"),
    })
    .describe("Data"),
  meta: zod
    .object({
      count: zod.number().describe("Count"),
    })
    .describe("Meta"),
});

export type StationListReply = zod.input<typeof StationListReply>;
export type StationListReplyOutput = zod.output<typeof StationListReply>;
