/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StreamIdInfoReply = zod.object({
  data: zod
    .object({
      stream: zod
        .object({
          streamId: zod.string().describe("Stream"),
          username: zod.string().describe("Username"),
          password: zod.string().describe("Password"),
          title: zod.string().describe("Title"),
          http: zod.string().describe("Http"),
          rtmp: zod.string().describe("Rtmp"),
          updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
          createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
        })
        .describe("Stream"),
    })
    .describe("Data"),
});

export type StreamIdInfoReply = zod.input<typeof StreamIdInfoReply>;
export type StreamIdInfoReplyOutput = zod.output<typeof StreamIdInfoReply>;
