/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StreamUpdateRequestDataStreamSchema = zod.object({
  username: zod.string().optional(),
  password: zod.string().optional(),
  title: zod.string().optional(),
  http: zod.string().optional(),
  rtmp: zod.string().optional(),
});

export type StreamUpdateRequestDataStreamSchema = zod.input<
  typeof StreamUpdateRequestDataStreamSchema
>;
export type StreamUpdateRequestDataStreamSchemaOutput = zod.output<
  typeof StreamUpdateRequestDataStreamSchema
>;
