/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StreamCreateDataStreamSchema = zod
  .object({
    username: zod.string(),
    password: zod.string(),
    title: zod.string(),
    http: zod.string(),
    rtmp: zod.string(),
  })
  .describe("Stream");

export type StreamCreateDataStreamSchema = zod.input<
  typeof StreamCreateDataStreamSchema
>;
export type StreamCreateDataStreamSchemaOutput = zod.output<
  typeof StreamCreateDataStreamSchema
>;
