/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StreamCreateResponseDataStreamSchema = zod.object({
  streamId: zod.string(),
  username: zod.string(),
  password: zod.string(),
  title: zod.string(),
  http: zod.string(),
  rtmp: zod.string(),
  updatedAt: zod.iso.datetime({ offset: true }),
  createdAt: zod.iso.datetime({ offset: true }),
});

export type StreamCreateResponseDataStreamSchema = zod.input<
  typeof StreamCreateResponseDataStreamSchema
>;
export type StreamCreateResponseDataStreamSchemaOutput = zod.output<
  typeof StreamCreateResponseDataStreamSchema
>;
