/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StreamCreateSchema = zod.object({
  data: zod
    .object({
      stream: zod
        .object({
          username: zod.string().describe("Username"),
          password: zod.string().describe("Password"),
          title: zod.string().describe("Title"),
          http: zod.string().describe("Http"),
          rtmp: zod.string().describe("Rtmp"),
        })
        .describe("Stream"),
    })
    .describe("Data"),
});

export type StreamCreateSchema = zod.input<typeof StreamCreateSchema>;
export type StreamCreateSchemaOutput = zod.output<typeof StreamCreateSchema>;
