/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StreamUpdateReplyData = zod.object({
  stream: zod
    .object({
      streamId: zod.string().describe("Stream"),
      username: zod.string().describe("Username"),
      password: zod.string().describe("Password"),
      title: zod.string().describe("Title"),
      http: zod.string().describe("Http"),
      rtmp: zod.string().describe("Rtmp"),
      updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
      createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
    })
    .describe("Stream"),
});

export type StreamUpdateReplyData = zod.input<typeof StreamUpdateReplyData>;
export type StreamUpdateReplyDataOutput = zod.output<
  typeof StreamUpdateReplyData
>;
