/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StreamCreateRequestSchema = zod.object({
  data: zod.object({
    stream: zod.object({
      username: zod.string(),
      password: zod.string(),
      title: zod.string(),
      http: zod.string(),
      rtmp: zod.string(),
    }),
  }),
});

export type StreamCreateRequestSchema = zod.input<
  typeof StreamCreateRequestSchema
>;
export type StreamCreateRequestSchemaOutput = zod.output<
  typeof StreamCreateRequestSchema
>;
