/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StreamCreateSchemaDataStream = zod.object({
  username: zod.string().describe("Username"),
  password: zod.string().describe("Password"),
  title: zod.string().describe("Title"),
  http: zod.string().describe("Http"),
  rtmp: zod.string().describe("Rtmp"),
});

export type StreamCreateSchemaDataStream = zod.input<
  typeof StreamCreateSchemaDataStream
>;
export type StreamCreateSchemaDataStreamOutput = zod.output<
  typeof StreamCreateSchemaDataStream
>;
