/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StreamCreateSchemaData = zod.object({
  stream: zod
    .object({
      username: zod.string().describe("Username"),
      password: zod.string().describe("Password"),
      title: zod.string().describe("Title"),
      http: zod.string().describe("Http"),
      rtmp: zod.string().describe("Rtmp"),
    })
    .describe("Stream"),
});

export type StreamCreateSchemaData = zod.input<typeof StreamCreateSchemaData>;
export type StreamCreateSchemaDataOutput = zod.output<
  typeof StreamCreateSchemaData
>;
