/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StreamIdUpdateSchemaDataStream = zod.object({
  username: zod.string().optional().describe("Username"),
  password: zod.string().optional().describe("Password"),
  title: zod.string().optional().describe("Title"),
  http: zod.string().optional().describe("Http"),
  rtmp: zod.string().optional().describe("Rtmp"),
});

export type StreamIdUpdateSchemaDataStream = zod.input<
  typeof StreamIdUpdateSchemaDataStream
>;
export type StreamIdUpdateSchemaDataStreamOutput = zod.output<
  typeof StreamIdUpdateSchemaDataStream
>;
