/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StreamUpdateSchema = zod
  .object({
    data: zod
      .object({
        stream: zod
          .object({
            username: zod.string().optional(),
            password: zod.string().optional(),
            title: zod.string().optional(),
            http: zod.string().optional(),
            rtmp: zod.string().optional(),
          })
          .describe("Stream"),
      })
      .describe("Data"),
  })
  .describe("Update");

export type StreamUpdateSchema = zod.input<typeof StreamUpdateSchema>;
export type StreamUpdateSchemaOutput = zod.output<typeof StreamUpdateSchema>;
