/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StreamCreateRequestDataStreamSchema = zod.object({
  username: zod.string(),
  password: zod.string(),
  title: zod.string(),
  http: zod.string(),
  rtmp: zod.string(),
});

export type StreamCreateRequestDataStreamSchema = zod.input<
  typeof StreamCreateRequestDataStreamSchema
>;
export type StreamCreateRequestDataStreamSchemaOutput = zod.output<
  typeof StreamCreateRequestDataStreamSchema
>;
