/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StreamInfoReplyData = zod.object({
  stream: zod
    .object({
      streamId: zod.string().describe("Stream"),
      username: zod.string().describe("Username"),
      password: zod.string().describe("Password"),
      title: zod.string().describe("Title"),
      http: zod.string().describe("Http"),
      rtmp: zod.string().describe("Rtmp"),
      updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
      createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
    })
    .describe("Stream"),
});

export type StreamInfoReplyData = zod.input<typeof StreamInfoReplyData>;
export type StreamInfoReplyDataOutput = zod.output<typeof StreamInfoReplyData>;
