/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StreamUpdateSchemaDataStream = zod.object({
  username: zod.string().optional().describe("Username"),
  password: zod.string().optional().describe("Password"),
  title: zod.string().optional().describe("Title"),
  http: zod.string().optional().describe("Http"),
  rtmp: zod.string().optional().describe("Rtmp"),
});

export type StreamUpdateSchemaDataStream = zod.input<
  typeof StreamUpdateSchemaDataStream
>;
export type StreamUpdateSchemaDataStreamOutput = zod.output<
  typeof StreamUpdateSchemaDataStream
>;
