/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const StreamControllerHandleStreamCreateBody = zod.object({
  data: zod
    .object({
      stream: zod
        .object({
          username: zod.string().describe("Username"),
          password: zod.string().describe("Password"),
          title: zod.string().describe("Title"),
          http: zod.string().describe("Http"),
          rtmp: zod.string().describe("Rtmp"),
        })
        .describe("Stream"),
    })
    .describe("Data"),
});

export type StreamControllerHandleStreamCreateBody = zod.input<
  typeof StreamControllerHandleStreamCreateBody
>;
export type StreamControllerHandleStreamCreateBodyOutput = zod.output<
  typeof StreamControllerHandleStreamCreateBody
>;
