/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TerminalListResponseSchema = zod.object({
  data: zod.object({
    terminals: zod.array(
      zod.object({
        terminalId: zod.string(),
        title: zod.string(),
        url: zod.string(),
        updatedAt: zod.iso.datetime({ offset: true }),
        createdAt: zod.iso.datetime({ offset: true }),
      }),
    ),
  }),
});

export type TerminalListResponseSchema = zod.input<
  typeof TerminalListResponseSchema
>;
export type TerminalListResponseSchemaOutput = zod.output<
  typeof TerminalListResponseSchema
>;
