/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TerminalUpdateReply = zod.object({
  data: zod
    .object({
      terminal: zod
        .object({
          terminalId: zod.string().describe("Terminal"),
          title: zod.string().describe("Title"),
          url: zod.string().describe("Url"),
          updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
          createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
        })
        .describe("Terminal"),
    })
    .describe("Data"),
});

export type TerminalUpdateReply = zod.input<typeof TerminalUpdateReply>;
export type TerminalUpdateReplyOutput = zod.output<typeof TerminalUpdateReply>;
