/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TerminalUpdateDataSchema = zod
  .object({
    terminal: zod
      .object({
        title: zod.string().optional(),
        url: zod.string().optional(),
      })
      .describe("Terminal"),
  })
  .describe("Data");

export type TerminalUpdateDataSchema = zod.input<
  typeof TerminalUpdateDataSchema
>;
export type TerminalUpdateDataSchemaOutput = zod.output<
  typeof TerminalUpdateDataSchema
>;
