/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TerminalCreateSchemaDataTerminal = zod.object({
  title: zod.string().describe("Title"),
  url: zod.string().describe("Url"),
});

export type TerminalCreateSchemaDataTerminal = zod.input<
  typeof TerminalCreateSchemaDataTerminal
>;
export type TerminalCreateSchemaDataTerminalOutput = zod.output<
  typeof TerminalCreateSchemaDataTerminal
>;
