/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TerminalUpdateRequestSchema = zod.object({
  data: zod.object({
    terminal: zod.object({
      title: zod.string().optional(),
      url: zod.string().optional(),
    }),
  }),
});

export type TerminalUpdateRequestSchema = zod.input<
  typeof TerminalUpdateRequestSchema
>;
export type TerminalUpdateRequestSchemaOutput = zod.output<
  typeof TerminalUpdateRequestSchema
>;
