/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TerminalUpdateSchema = zod.object({
  data: zod
    .object({
      terminal: zod
        .object({
          title: zod.string().optional().describe("Title"),
          url: zod.string().optional().describe("Url"),
        })
        .describe("Terminal"),
    })
    .describe("Data"),
});

export type TerminalUpdateSchema = zod.input<typeof TerminalUpdateSchema>;
export type TerminalUpdateSchemaOutput = zod.output<
  typeof TerminalUpdateSchema
>;
