/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TerminalCreateSchemaData = zod.object({
  terminal: zod
    .object({
      title: zod.string().describe("Title"),
      url: zod.string().describe("Url"),
    })
    .describe("Terminal"),
});

export type TerminalCreateSchemaData = zod.input<
  typeof TerminalCreateSchemaData
>;
export type TerminalCreateSchemaDataOutput = zod.output<
  typeof TerminalCreateSchemaData
>;
