/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TerminalControllerHandleTerminalCreateBody = zod.object({
  data: zod
    .object({
      terminal: zod
        .object({
          title: zod.string().describe("Title"),
          url: zod.string().describe("Url"),
        })
        .describe("Terminal"),
    })
    .describe("Data"),
});

export type TerminalControllerHandleTerminalCreateBody = zod.input<
  typeof TerminalControllerHandleTerminalCreateBody
>;
export type TerminalControllerHandleTerminalCreateBodyOutput = zod.output<
  typeof TerminalControllerHandleTerminalCreateBody
>;
