/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TerminalCreateDataSchema = zod
  .object({
    terminal: zod
      .object({
        title: zod.string(),
        url: zod.string(),
      })
      .describe("Terminal"),
  })
  .describe("Data");

export type TerminalCreateDataSchema = zod.input<
  typeof TerminalCreateDataSchema
>;
export type TerminalCreateDataSchemaOutput = zod.output<
  typeof TerminalCreateDataSchema
>;
