/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TerminalUpdateRequestDataTerminalSchema = zod.object({
  title: zod.string().optional(),
  url: zod.string().optional(),
});

export type TerminalUpdateRequestDataTerminalSchema = zod.input<
  typeof TerminalUpdateRequestDataTerminalSchema
>;
export type TerminalUpdateRequestDataTerminalSchemaOutput = zod.output<
  typeof TerminalUpdateRequestDataTerminalSchema
>;
