/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TerminalCreateRequestSchema = zod.object({
  data: zod.object({
    terminal: zod.object({
      title: zod.string(),
      url: zod.string(),
    }),
  }),
});

export type TerminalCreateRequestSchema = zod.input<
  typeof TerminalCreateRequestSchema
>;
export type TerminalCreateRequestSchemaOutput = zod.output<
  typeof TerminalCreateRequestSchema
>;
