/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TerminalUpdateRequestDataSchema = zod.object({
  terminal: zod.object({
    title: zod.string().optional(),
    url: zod.string().optional(),
  }),
});

export type TerminalUpdateRequestDataSchema = zod.input<
  typeof TerminalUpdateRequestDataSchema
>;
export type TerminalUpdateRequestDataSchemaOutput = zod.output<
  typeof TerminalUpdateRequestDataSchema
>;
