/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TerminalCreateDataTerminalSchema = zod
  .object({
    title: zod.string(),
    url: zod.string(),
  })
  .describe("Terminal");

export type TerminalCreateDataTerminalSchema = zod.input<
  typeof TerminalCreateDataTerminalSchema
>;
export type TerminalCreateDataTerminalSchemaOutput = zod.output<
  typeof TerminalCreateDataTerminalSchema
>;
