/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TerminalCreateRequestDataSchema = zod.object({
  terminal: zod.object({
    title: zod.string(),
    url: zod.string(),
  }),
});

export type TerminalCreateRequestDataSchema = zod.input<
  typeof TerminalCreateRequestDataSchema
>;
export type TerminalCreateRequestDataSchemaOutput = zod.output<
  typeof TerminalCreateRequestDataSchema
>;
