/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TerminalCreateRequestDataTerminalSchema = zod.object({
  title: zod.string(),
  url: zod.string(),
});

export type TerminalCreateRequestDataTerminalSchema = zod.input<
  typeof TerminalCreateRequestDataTerminalSchema
>;
export type TerminalCreateRequestDataTerminalSchemaOutput = zod.output<
  typeof TerminalCreateRequestDataTerminalSchema
>;
