/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TerminalUpdateDataTerminalSchema = zod
  .object({
    title: zod.string().optional(),
    url: zod.string().optional(),
  })
  .describe("Terminal");

export type TerminalUpdateDataTerminalSchema = zod.input<
  typeof TerminalUpdateDataTerminalSchema
>;
export type TerminalUpdateDataTerminalSchemaOutput = zod.output<
  typeof TerminalUpdateDataTerminalSchema
>;
