/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TournamentUpdateDataSchema = zod
  .object({
    tournament: zod
      .object({
        timeout: zod.number().optional(),
        title: zod.string().optional(),
        url: zod.string().optional(),
      })
      .describe("Tournament"),
  })
  .describe("Data");

export type TournamentUpdateDataSchema = zod.input<
  typeof TournamentUpdateDataSchema
>;
export type TournamentUpdateDataSchemaOutput = zod.output<
  typeof TournamentUpdateDataSchema
>;
