/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TournamentControllerHandleTournamentCreateBody = zod.object({
  data: zod.object({
    tournament: zod.object({
      timeout: zod.number(),
      title: zod.string(),
    }),
  }),
});

export type TournamentControllerHandleTournamentCreateBody = zod.input<
  typeof TournamentControllerHandleTournamentCreateBody
>;
export type TournamentControllerHandleTournamentCreateBodyOutput = zod.output<
  typeof TournamentControllerHandleTournamentCreateBody
>;
