/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TournamentUpdateRequestDataSchema = zod.object({
  tournament: zod.object({
    timeout: zod.number().optional(),
    title: zod.string().optional(),
    url: zod.string().optional(),
  }),
});

export type TournamentUpdateRequestDataSchema = zod.input<
  typeof TournamentUpdateRequestDataSchema
>;
export type TournamentUpdateRequestDataSchemaOutput = zod.output<
  typeof TournamentUpdateRequestDataSchema
>;
