/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TournamentListReply = zod.object({
  data: zod
    .object({
      tournaments: zod
        .array(
          zod.object({
            tournamentId: zod.string().describe("Tournament"),
            timeout: zod.number().describe("Timeout"),
            title: zod.string().describe("Title"),
            from: zod.iso.datetime({ offset: true }).describe("From"),
            to: zod.iso.datetime({ offset: true }).describe("To"),
            updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
            createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
          }),
        )
        .describe("Tournaments"),
    })
    .describe("Data"),
  meta: zod
    .object({
      count: zod.number().describe("Count"),
    })
    .describe("Meta"),
});

export type TournamentListReply = zod.input<typeof TournamentListReply>;
export type TournamentListReplyOutput = zod.output<typeof TournamentListReply>;
