/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TournamentCreateDataTournamentSchema = zod
  .object({
    timeout: zod.number(),
    title: zod.string(),
  })
  .describe("Tournament");

export type TournamentCreateDataTournamentSchema = zod.input<
  typeof TournamentCreateDataTournamentSchema
>;
export type TournamentCreateDataTournamentSchemaOutput = zod.output<
  typeof TournamentCreateDataTournamentSchema
>;
