/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TournamentUpdateSchemaDataTournament = zod.object({
  timeout: zod.number().optional().describe("Timeout"),
  title: zod.string().optional().describe("Title"),
  url: zod.string().optional().describe("Url"),
});

export type TournamentUpdateSchemaDataTournament = zod.input<
  typeof TournamentUpdateSchemaDataTournament
>;
export type TournamentUpdateSchemaDataTournamentOutput = zod.output<
  typeof TournamentUpdateSchemaDataTournament
>;
