/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TournamentUpdateSchema = zod
  .object({
    data: zod
      .object({
        tournament: zod
          .object({
            timeout: zod.number().optional(),
            title: zod.string().optional(),
            url: zod.string().optional(),
          })
          .describe("Tournament"),
      })
      .describe("Data"),
  })
  .describe("Update");

export type TournamentUpdateSchema = zod.input<typeof TournamentUpdateSchema>;
export type TournamentUpdateSchemaOutput = zod.output<
  typeof TournamentUpdateSchema
>;
