/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TournamentListReplyDataTournament = zod.object({
  tournamentId: zod.string().describe("Tournament"),
  timeout: zod.number().describe("Timeout"),
  title: zod.string().describe("Title"),
  from: zod.iso.datetime({ offset: true }).describe("From"),
  to: zod.iso.datetime({ offset: true }).describe("To"),
  updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
  createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
});

export type TournamentListReplyDataTournament = zod.input<
  typeof TournamentListReplyDataTournament
>;
export type TournamentListReplyDataTournamentOutput = zod.output<
  typeof TournamentListReplyDataTournament
>;
