/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TournamentCreateRequestDataTournamentSchema = zod.object({
  timeout: zod.number(),
  title: zod.string(),
});

export type TournamentCreateRequestDataTournamentSchema = zod.input<
  typeof TournamentCreateRequestDataTournamentSchema
>;
export type TournamentCreateRequestDataTournamentSchemaOutput = zod.output<
  typeof TournamentCreateRequestDataTournamentSchema
>;
