/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TournamentInfoResponseDataSchema = zod.object({
  tournament: zod.object({
    tournamentId: zod.string(),
    timeout: zod.number(),
    status: zod.enum([
      "SCHEDULED",
      "CANCELLED",
      "FINISHED",
      "UNKNOWN",
      "STARTED",
    ]),
    title: zod.string(),
    url: zod.string(),
    updatedAt: zod.iso.datetime({ offset: true }),
    createdAt: zod.iso.datetime({ offset: true }),
  }),
});

export type TournamentInfoResponseDataSchema = zod.input<
  typeof TournamentInfoResponseDataSchema
>;
export type TournamentInfoResponseDataSchemaOutput = zod.output<
  typeof TournamentInfoResponseDataSchema
>;
