/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TournamentCreateSchemaDataTournament = zod.object({
  timeout: zod.number().describe("Timeout"),
  title: zod.string().describe("Title"),
});

export type TournamentCreateSchemaDataTournament = zod.input<
  typeof TournamentCreateSchemaDataTournament
>;
export type TournamentCreateSchemaDataTournamentOutput = zod.output<
  typeof TournamentCreateSchemaDataTournament
>;
