/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TournamentCreateDataSchema = zod
  .object({
    tournament: zod
      .object({
        timeout: zod.number(),
        title: zod.string(),
      })
      .describe("Tournament"),
  })
  .describe("Data");

export type TournamentCreateDataSchema = zod.input<
  typeof TournamentCreateDataSchema
>;
export type TournamentCreateDataSchemaOutput = zod.output<
  typeof TournamentCreateDataSchema
>;
