/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TournamentControllerHandleTournamentUpdateBody = zod.object({
  data: zod
    .object({
      tournament: zod
        .object({
          timeout: zod.number().optional().describe("Timeout"),
          title: zod.string().optional().describe("Title"),
          url: zod.string().optional().describe("Url"),
        })
        .describe("Tournament"),
    })
    .describe("Data"),
});

export type TournamentControllerHandleTournamentUpdateBody = zod.input<
  typeof TournamentControllerHandleTournamentUpdateBody
>;
export type TournamentControllerHandleTournamentUpdateBodyOutput = zod.output<
  typeof TournamentControllerHandleTournamentUpdateBody
>;
