/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TournamentCancelReplyData = zod.object({
  tournament: zod
    .object({
      tournamentId: zod.string().describe("Tournament"),
      timeout: zod.number().describe("Timeout"),
      status: zod
        .enum(["SCHEDULED", "CANCELLED", "FINISHED", "UNKNOWN", "STARTED"])
        .describe("Status"),
      title: zod.string().describe("Title"),
      url: zod.string().describe("Url"),
      updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
      createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
    })
    .describe("Tournament"),
});

export type TournamentCancelReplyData = zod.input<
  typeof TournamentCancelReplyData
>;
export type TournamentCancelReplyDataOutput = zod.output<
  typeof TournamentCancelReplyData
>;
