/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TournamentUpdateSchemaData = zod.object({
  tournament: zod
    .object({
      timeout: zod.number().optional().describe("Timeout"),
      title: zod.string().optional().describe("Title"),
      url: zod.string().optional().describe("Url"),
    })
    .describe("Tournament"),
});

export type TournamentUpdateSchemaData = zod.input<
  typeof TournamentUpdateSchemaData
>;
export type TournamentUpdateSchemaDataOutput = zod.output<
  typeof TournamentUpdateSchemaData
>;
