/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TournamentCreateSchemaData = zod.object({
  tournament: zod
    .object({
      timeout: zod.number().describe("Timeout"),
      title: zod.string().describe("Title"),
      from: zod.iso.datetime({ offset: true }).describe("From"),
      to: zod.iso.datetime({ offset: true }).describe("To"),
    })
    .describe("Tournament"),
});

export type TournamentCreateSchemaData = zod.input<
  typeof TournamentCreateSchemaData
>;
export type TournamentCreateSchemaDataOutput = zod.output<
  typeof TournamentCreateSchemaData
>;
