/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TournamentInfoResponseSchema = zod.object({
  data: zod.object({
    tournament: zod.object({
      tournamentId: zod.string(),
      timeout: zod.number(),
      status: zod.enum([
        "SCHEDULED",
        "CANCELLED",
        "FINISHED",
        "UNKNOWN",
        "STARTED",
      ]),
      title: zod.string(),
      url: zod.string(),
      updatedAt: zod.iso.datetime({ offset: true }),
      createdAt: zod.iso.datetime({ offset: true }),
    }),
  }),
});

export type TournamentInfoResponseSchema = zod.input<
  typeof TournamentInfoResponseSchema
>;
export type TournamentInfoResponseSchemaOutput = zod.output<
  typeof TournamentInfoResponseSchema
>;
