/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const TournamentIdUpdateSchemaDataTournament = zod.object({
  timeout: zod.number().optional().describe("Timeout"),
  title: zod.string().optional().describe("Title"),
  from: zod.iso.datetime({ offset: true }).optional().describe("From"),
  to: zod.iso.datetime({ offset: true }).optional().describe("To"),
});

export type TournamentIdUpdateSchemaDataTournament = zod.input<
  typeof TournamentIdUpdateSchemaDataTournament
>;
export type TournamentIdUpdateSchemaDataTournamentOutput = zod.output<
  typeof TournamentIdUpdateSchemaDataTournament
>;
