/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const VenueListResponseDataVenueSchema = zod.object({
  venueId: zod.string(),
  terminalId: zod.string(),
  overlayId: zod.string(),
  streamId: zod.string(),
  title: zod.string(),
  key: zod.string(),
  updatedAt: zod.iso.datetime({ offset: true }),
  createdAt: zod.iso.datetime({ offset: true }),
});

export type VenueListResponseDataVenueSchema = zod.input<
  typeof VenueListResponseDataVenueSchema
>;
export type VenueListResponseDataVenueSchemaOutput = zod.output<
  typeof VenueListResponseDataVenueSchema
>;
