/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const VenueIdUpdateSchema = zod.object({
  data: zod
    .object({
      venue: zod
        .object({
          stationId: zod.string().optional().describe("Station"),
          overlayId: zod.string().optional().describe("Overlay"),
          streamId: zod.string().optional().describe("Stream"),
          title: zod.string().optional().describe("Title"),
          key: zod.string().optional().describe("Key"),
        })
        .describe("Venue"),
    })
    .describe("Data"),
});

export type VenueIdUpdateSchema = zod.input<typeof VenueIdUpdateSchema>;
export type VenueIdUpdateSchemaOutput = zod.output<typeof VenueIdUpdateSchema>;
