/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const VenueCreateSchema = zod
  .object({
    data: zod
      .object({
        venue: zod
          .object({
            terminalId: zod.string(),
            overlayId: zod.string(),
            streamId: zod.string(),
            title: zod.string(),
            key: zod.string(),
          })
          .describe("Venue"),
      })
      .describe("Data"),
  })
  .describe("Create");

export type VenueCreateSchema = zod.input<typeof VenueCreateSchema>;
export type VenueCreateSchemaOutput = zod.output<typeof VenueCreateSchema>;
