/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const VenueListReplyData = zod.object({
  venues: zod
    .array(
      zod.object({
        venueId: zod.string().describe("Venue"),
        stationId: zod.string().describe("Station"),
        overlayId: zod.string().describe("Overlay"),
        streamId: zod.string().describe("Stream"),
        title: zod.string().describe("Title"),
        key: zod.string().describe("Key"),
        updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
        createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
      }),
    )
    .describe("Venues"),
});

export type VenueListReplyData = zod.input<typeof VenueListReplyData>;
export type VenueListReplyDataOutput = zod.output<typeof VenueListReplyData>;
