/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const VenueIdInfoReplyData = zod.object({
  venue: zod
    .object({
      venueId: zod.string().describe("Venue"),
      stationId: zod.string().describe("Station"),
      overlayId: zod.string().describe("Overlay"),
      streamId: zod.string().describe("Stream"),
      title: zod.string().describe("Title"),
      key: zod.string().describe("Key"),
      updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
      createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
    })
    .describe("Venue"),
});

export type VenueIdInfoReplyData = zod.input<typeof VenueIdInfoReplyData>;
export type VenueIdInfoReplyDataOutput = zod.output<
  typeof VenueIdInfoReplyData
>;
