/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const VenueUpdateSchemaDataVenue = zod.object({
  title: zod.string().optional().describe("Title"),
  key: zod.string().optional().describe("Key"),
});

export type VenueUpdateSchemaDataVenue = zod.input<
  typeof VenueUpdateSchemaDataVenue
>;
export type VenueUpdateSchemaDataVenueOutput = zod.output<
  typeof VenueUpdateSchemaDataVenue
>;
