/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const VenueCreateSchemaData = zod.object({
  venue: zod
    .object({
      stationId: zod.string().describe("Station"),
      overlayId: zod.string().describe("Overlay"),
      streamId: zod.string().describe("Stream"),
      title: zod.string().describe("Title"),
      key: zod.string().optional().describe("Key"),
    })
    .describe("Venue"),
});

export type VenueCreateSchemaData = zod.input<typeof VenueCreateSchemaData>;
export type VenueCreateSchemaDataOutput = zod.output<
  typeof VenueCreateSchemaData
>;
