/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const VenueIdInfoReplyMeta = zod.object({
  overlay: zod.string().describe("Overlay"),
  station: zod.string().describe("Station"),
  rtmp: zod.string().describe("Rtmp"),
  http: zod.string().describe("Http"),
});

export type VenueIdInfoReplyMeta = zod.input<typeof VenueIdInfoReplyMeta>;
export type VenueIdInfoReplyMetaOutput = zod.output<
  typeof VenueIdInfoReplyMeta
>;
