/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const VenueUpdateReplyData = zod.object({
  venue: zod
    .object({
      venueId: zod.string().describe("Venue"),
      terminalId: zod.string().describe("Terminal"),
      overlayId: zod.string().describe("Overlay"),
      streamId: zod.string().describe("Stream"),
      title: zod.string().describe("Title"),
      key: zod.string().describe("Key"),
      updatedAt: zod.iso.datetime({ offset: true }).describe("Updated"),
      createdAt: zod.iso.datetime({ offset: true }).describe("Created"),
    })
    .describe("Venue"),
});

export type VenueUpdateReplyData = zod.input<typeof VenueUpdateReplyData>;
export type VenueUpdateReplyDataOutput = zod.output<
  typeof VenueUpdateReplyData
>;
