/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const VenueUpdateRequestDataVenueSchema = zod.object({
  title: zod.string().optional(),
  key: zod.string().optional(),
});

export type VenueUpdateRequestDataVenueSchema = zod.input<
  typeof VenueUpdateRequestDataVenueSchema
>;
export type VenueUpdateRequestDataVenueSchemaOutput = zod.output<
  typeof VenueUpdateRequestDataVenueSchema
>;
