/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Documentation
 * Documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const VenueCreateSchemaDataVenue = zod.object({
  stationId: zod.string().describe("Station"),
  overlayId: zod.string().describe("Overlay"),
  streamId: zod.string().describe("Stream"),
  title: zod.string().describe("Title"),
  key: zod.string().optional().describe("Key"),
});

export type VenueCreateSchemaDataVenue = zod.input<
  typeof VenueCreateSchemaDataVenue
>;
export type VenueCreateSchemaDataVenueOutput = zod.output<
  typeof VenueCreateSchemaDataVenue
>;
