/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const VenueUpdateDataSchema = zod
  .object({
    venue: zod
      .object({
        title: zod.string().optional(),
        key: zod.string().optional(),
      })
      .describe("Venue"),
  })
  .describe("Data");

export type VenueUpdateDataSchema = zod.input<typeof VenueUpdateDataSchema>;
export type VenueUpdateDataSchemaOutput = zod.output<
  typeof VenueUpdateDataSchema
>;
