/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const VenueCreateSchemaDataVenue = zod.object({
  terminalId: zod.string().describe("Terminal"),
  overlayId: zod.string().describe("Overlay"),
  streamId: zod.string().describe("Stream"),
  title: zod.string().describe("Title"),
  key: zod.string().describe("Key"),
});

export type VenueCreateSchemaDataVenue = zod.input<
  typeof VenueCreateSchemaDataVenue
>;
export type VenueCreateSchemaDataVenueOutput = zod.output<
  typeof VenueCreateSchemaDataVenue
>;
