/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const VenueUpdateDataVenueSchema = zod
  .object({
    title: zod.string().optional(),
    key: zod.string().optional(),
  })
  .describe("Venue");

export type VenueUpdateDataVenueSchema = zod.input<
  typeof VenueUpdateDataVenueSchema
>;
export type VenueUpdateDataVenueSchemaOutput = zod.output<
  typeof VenueUpdateDataVenueSchema
>;
