/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const VenueUpdateRequestSchema = zod.object({
  data: zod.object({
    venue: zod.object({
      title: zod.string().optional(),
      key: zod.string().optional(),
    }),
  }),
});

export type VenueUpdateRequestSchema = zod.input<
  typeof VenueUpdateRequestSchema
>;
export type VenueUpdateRequestSchemaOutput = zod.output<
  typeof VenueUpdateRequestSchema
>;
