/**
 * Generated by orval v8.21.0 🍺
 * Do not edit manually.
 * Manager documentation
 * Manager documentation for cyberleague
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from "zod";

export const VenueListResponseSchema = zod.object({
  data: zod.object({
    venues: zod.array(
      zod.object({
        venueId: zod.string(),
        terminalId: zod.string(),
        overlayId: zod.string(),
        streamId: zod.string(),
        title: zod.string(),
        key: zod.string(),
        updatedAt: zod.iso.datetime({ offset: true }),
        createdAt: zod.iso.datetime({ offset: true }),
      }),
    ),
  }),
});

export type VenueListResponseSchema = zod.input<typeof VenueListResponseSchema>;
export type VenueListResponseSchemaOutput = zod.output<
  typeof VenueListResponseSchema
>;
