/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tournament/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TournamentController_handleTournamentCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournament/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TournamentController_handleTournamentList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournament/{tournamentId}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TournamentController_handleTournamentInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournament/{tournamentId}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["TournamentController_handleTournamentUpdate"];
        trace?: never;
    };
    "/tournament/{tournamentId}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TournamentController_handleTournamentSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournament/{tournamentId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TournamentController_handleTournamentStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournament/{tournamentId}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TournamentController_handleTournamentFinish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tournament/{tournamentId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TournamentController_handleTournamentCancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/terminal/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["TerminalController_handleTerminalCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/terminal/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TerminalController_handleTerminalList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/terminal/{terminalId}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TerminalController_handleTerminalInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/terminal/{terminalId}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["TerminalController_handleTerminalUpdate"];
        trace?: never;
    };
    "/overlay/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["OverlayController_handleOverlayCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overlay/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OverlayController_handleOverlayList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overlay/{overlayId}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OverlayController_handleOverlayInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overlay/{overlayId}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["OverlayController_handleOverlayUpdate"];
        trace?: never;
    };
    "/health/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_handleHealthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StreamController_handleStreamCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StreamController_handleStreamList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream/{streamId}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["StreamController_handleStreamInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream/{streamId}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["StreamController_handleStreamUpdate"];
        trace?: never;
    };
    "/boxer/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BoxerController_handleBoxerCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boxer/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BoxerController_handleBoxerList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boxer/{boxerId}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BoxerController_handleBoxerInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/boxer/{boxerId}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["BoxerController_handleBoxerUpdate"];
        trace?: never;
    };
    "/event/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EventController_handleEventCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EventController_handleEventList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event/{eventId}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["EventController_handleEventInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event/{eventId}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["EventController_handleEventUpdate"];
        trace?: never;
    };
    "/event/{eventId}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EventController_handleEventSchedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event/{eventId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EventController_handleEventStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event/{eventId}/finish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EventController_handleEventFinish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event/{eventId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["EventController_handleEventCancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venue/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["VenueController_handleVenueCreate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venue/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["VenueController_handleVenueList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venue/{venueId}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["VenueController_handleVenueInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/venue/{venueId}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["VenueController_handleVenueUpdate"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Tournament */
        TournamentCreateDataTournamentSchema: {
            /** Timeout */
            timeout: number;
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** @description Data */
        TournamentCreateDataSchema: {
            /** Tournament */
            tournament: components["schemas"]["TournamentCreateDataTournamentSchema"];
        };
        /** @description Create */
        TournamentCreateSchema: {
            /** Data */
            data: components["schemas"]["TournamentCreateDataSchema"];
        };
        /** @description Tournament */
        TournamentUpdateDataTournamentSchema: {
            /** Timeout */
            timeout?: number;
            /** Title */
            title?: string;
            /** Url */
            url?: string;
        };
        /** @description Data */
        TournamentUpdateDataSchema: {
            /** Tournament */
            tournament: components["schemas"]["TournamentUpdateDataTournamentSchema"];
        };
        /** @description Update */
        TournamentUpdateSchema: {
            /** Data */
            data: components["schemas"]["TournamentUpdateDataSchema"];
        };
        /** @description Terminal */
        TerminalCreateDataTerminalSchema: {
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** @description Data */
        TerminalCreateDataSchema: {
            /** Terminal */
            terminal: components["schemas"]["TerminalCreateDataTerminalSchema"];
        };
        /** @description Create */
        TerminalCreateSchema: {
            /** Data */
            data: components["schemas"]["TerminalCreateDataSchema"];
        };
        /** @description Terminal */
        TerminalUpdateDataTerminalSchema: {
            /** Title */
            title?: string;
            /** Url */
            url?: string;
        };
        /** @description Data */
        TerminalUpdateDataSchema: {
            /** Terminal */
            terminal: components["schemas"]["TerminalUpdateDataTerminalSchema"];
        };
        /** @description Update */
        TerminalUpdateSchema: {
            /** Data */
            data: components["schemas"]["TerminalUpdateDataSchema"];
        };
        /** @description Overlay */
        OverlayCreateDataOverlaySchema: {
            /** Title */
            title: string;
            /** Url */
            url: string;
        };
        /** @description Data */
        OverlayCreateDataSchema: {
            /** Overlay */
            overlay: components["schemas"]["OverlayCreateDataOverlaySchema"];
        };
        /** @description Create */
        OverlayCreateSchema: {
            /** Data */
            data: components["schemas"]["OverlayCreateDataSchema"];
        };
        /** @description Overlay */
        OverlayUpdateDataOverlaySchema: {
            /** Title */
            title?: string;
            /** Url */
            url?: string;
        };
        /** @description Data */
        OverlayUpdateDataSchema: {
            /** Overlay */
            overlay: components["schemas"]["OverlayUpdateDataOverlaySchema"];
        };
        /** @description Update */
        OverlayUpdateSchema: {
            /** Data */
            data: components["schemas"]["OverlayUpdateDataSchema"];
        };
        /** @description Stream */
        StreamCreateDataStreamSchema: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /** Title */
            title: string;
            /** Http */
            http: string;
            /** Rtmp */
            rtmp: string;
        };
        /** @description Data */
        StreamCreateDataSchema: {
            /** Stream */
            stream: components["schemas"]["StreamCreateDataStreamSchema"];
        };
        /** @description Create */
        StreamCreateSchema: {
            /** Data */
            data: components["schemas"]["StreamCreateDataSchema"];
        };
        /** @description Stream */
        StreamUpdateDataStreamSchema: {
            /** Username */
            username?: string;
            /** Password */
            password?: string;
            /** Title */
            title?: string;
            /** Http */
            http?: string;
            /** Rtmp */
            rtmp?: string;
        };
        /** @description Data */
        StreamUpdateDataSchema: {
            /** Stream */
            stream: components["schemas"]["StreamUpdateDataStreamSchema"];
        };
        /** @description Update */
        StreamUpdateSchema: {
            /** Data */
            data: components["schemas"]["StreamUpdateDataSchema"];
        };
        /** @description Boxer */
        BoxerCreateDataBoxerSchema: {
            /** Fullname */
            fullname: string;
        };
        /** @description Data */
        BoxerCreateDataSchema: {
            /** Boxer */
            boxer: components["schemas"]["BoxerCreateDataBoxerSchema"];
        };
        /** @description Create */
        BoxerCreateSchema: {
            /** Data */
            data: components["schemas"]["BoxerCreateDataSchema"];
        };
        /** @description Boxer */
        BoxerUpdateDataBoxerSchema: {
            /** Fullname */
            fullname?: string;
        };
        /** @description Data */
        BoxerUpdateDataSchema: {
            /** Boxer */
            boxer: components["schemas"]["BoxerUpdateDataBoxerSchema"];
        };
        /** @description Update */
        BoxerUpdateSchema: {
            /** Data */
            data: components["schemas"]["BoxerUpdateDataSchema"];
        };
        /** @description Event */
        EventCreateDataEventSchema: {
            /** Tournament */
            tournamentId: string;
            /** Venue */
            venueId: string;
            /** Blue */
            blueId: string;
            /** Red */
            redId: string;
            /**
             * Schedule
             * Format: date-time
             */
            schedule: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "UNKNOWN" | "MANUAL" | "AUTO";
        };
        /** @description Data */
        EventCreateDataSchema: {
            /** Event */
            event: components["schemas"]["EventCreateDataEventSchema"];
        };
        /** @description Create */
        EventCreateSchema: {
            /** Data */
            data: components["schemas"]["EventCreateDataSchema"];
        };
        /** @description Event */
        EventUpdateDataEventSchema: {
            /**
             * Schedule
             * Format: date-time
             */
            schedule?: string;
            /** Title */
            title?: string;
            /**
             * Mode
             * @enum {string}
             */
            mode?: "UNKNOWN" | "MANUAL" | "AUTO";
            /** Url */
            url?: string;
        };
        /** @description Data */
        EventUpdateDataSchema: {
            /** Event */
            event: components["schemas"]["EventUpdateDataEventSchema"];
        };
        /** @description Update */
        EventUpdateSchema: {
            /** Data */
            data: components["schemas"]["EventUpdateDataSchema"];
        };
        /** @description Venue */
        VenueCreateDataVenueSchema: {
            /** Terminal */
            terminalId: string;
            /** Overlay */
            overlayId: string;
            /** Stream */
            streamId: string;
            /** Title */
            title: string;
            /** Key */
            key: string;
        };
        /** @description Data */
        VenueCreateDataSchema: {
            /** Venue */
            venue: components["schemas"]["VenueCreateDataVenueSchema"];
        };
        /** @description Create */
        VenueCreateSchema: {
            /** Data */
            data: components["schemas"]["VenueCreateDataSchema"];
        };
        /** @description Venue */
        VenueUpdateDataVenueSchema: {
            /** Title */
            title?: string;
            /** Key */
            key?: string;
        };
        /** @description Data */
        VenueUpdateDataSchema: {
            /** Venue */
            venue: components["schemas"]["VenueUpdateDataVenueSchema"];
        };
        /** @description Update */
        VenueUpdateSchema: {
            /** Data */
            data: components["schemas"]["VenueUpdateDataSchema"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    TournamentController_handleTournamentCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TournamentCreateSchema"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TournamentController_handleTournamentList: {
        parameters: {
            query?: {
                contains?: string;
                order?: "asc" | "desc";
                skip?: number;
                take?: number;
                by?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TournamentController_handleTournamentInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TournamentController_handleTournamentUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TournamentUpdateSchema"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TournamentController_handleTournamentSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TournamentController_handleTournamentStart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TournamentController_handleTournamentFinish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TournamentController_handleTournamentCancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tournamentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TerminalController_handleTerminalCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TerminalCreateSchema"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TerminalController_handleTerminalList: {
        parameters: {
            query?: {
                contains?: string;
                order?: "asc" | "desc";
                skip?: number;
                take?: number;
                by?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TerminalController_handleTerminalInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                terminalId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    TerminalController_handleTerminalUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                terminalId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TerminalUpdateSchema"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OverlayController_handleOverlayCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverlayCreateSchema"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OverlayController_handleOverlayList: {
        parameters: {
            query?: {
                contains?: string;
                order?: "asc" | "desc";
                skip?: number;
                take?: number;
                by?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OverlayController_handleOverlayInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                overlayId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    OverlayController_handleOverlayUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                overlayId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverlayUpdateSchema"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_handleHealthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StreamController_handleStreamCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamCreateSchema"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StreamController_handleStreamList: {
        parameters: {
            query?: {
                contains?: string;
                order?: "asc" | "desc";
                skip?: number;
                take?: number;
                by?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StreamController_handleStreamInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                streamId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    StreamController_handleStreamUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                streamId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StreamUpdateSchema"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BoxerController_handleBoxerCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoxerCreateSchema"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BoxerController_handleBoxerList: {
        parameters: {
            query?: {
                contains?: string;
                order?: "asc" | "desc";
                skip?: number;
                take?: number;
                by?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BoxerController_handleBoxerInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                boxerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    BoxerController_handleBoxerUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                boxerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BoxerUpdateSchema"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_handleEventCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventCreateSchema"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_handleEventList: {
        parameters: {
            query?: {
                contains?: string;
                order?: "asc" | "desc";
                skip?: number;
                take?: number;
                by?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_handleEventInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_handleEventUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventUpdateSchema"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_handleEventSchedule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_handleEventStart: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_handleEventFinish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    EventController_handleEventCancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VenueController_handleVenueCreate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VenueCreateSchema"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VenueController_handleVenueList: {
        parameters: {
            query?: {
                contains?: string;
                order?: "asc" | "desc";
                skip?: number;
                take?: number;
                by?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VenueController_handleVenueInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    VenueController_handleVenueUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                venueId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VenueUpdateSchema"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
